#!/bin/sh
# Function to get File

getFile(){

    # Reading txtFileName to convert it's content

    echo -n "Enter File Name:"

    read txtFileName

    # Checking if file exist

    if [ ! -f $txtFileName ]; then
        echo "File Name $txtFileName does not exists."
        exit 1
    fi
}
clear
  echo "1. Uppercase to Lowercase "
  echo "2. Lowercase to Uppercase"
  echo "3. Exit"
  echo -n "Enter your Choice(1-3):"
  read Ch
